### ISSUE TITLE
Projects do not load

### ISSUE THREAD

**Issue by ScolderCreations** [scratchbackup/scratchbackup.github.io#83]
currently, the website cannot recognize projects.

**Comment by hello-smile6** [comment]
> currently, the website cannot recognize projects.

Strange. I'll look into it soon, if you want. (can't access a desktop, currently signed in from a school laptop via chrome://chrome-signin )

**Comment by RunTheCoins** [comment]
Also, Th

> > currently, the website cannot recognize projects.
> 
> Strange. I'll look into it soon, if you want. (can't access a desktop, currently signed in from a school laptop via chrome://chrome-signin )

Don't know if this will help, but I've noticed the website now loads just a black screen...
I'm assuming this error from the console could help on pinpointing what the major problem is.

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at App.js:32:12
    at Array.filter (<anonymous>)
    at i.value (App.js:30:8)
    at $o (react-dom.production.min.js:187:188)
    at Qo (react-dom.production.min.js:186:173)
    at $i (react-dom.production.min.js:269:427)
    at Pu (react-dom.production.min.js:250:347)
    at xu (react-dom.production.min.js:250:278)
    at Au (react-dom.production.min.js:250:138)
    at vu (react-dom.production.min.js:243:163)

**Comment by RunTheCoins** [comment]
![Screen Shot 2022-02-01 at 2 18 18 PM](https://user-images.githubusercontent.com/81893577/152035967-acacd414-d43d-4301-8982-d5a24c2d6d8a.png)

**Comment by ScolderCreations** [comment]
It appears I may have messed something up… It has problems with search sorting.

**Comment by webdev03** [comment]
https://scratchbackup.github.io/projects.json is an array of project IDs. Let's say we are looking at ID 1. It's just a string, and string.title will be undefined. So you will need to either fetch from the Scratch API or change the structure of your array to contain the title as well.
